version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:5000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
