name: Build and Push Docker Images

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push frontend image
        run: |
          cd frontend/bookstore-frontend
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

      - name: Build and push backend image
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and push Docker Compose services
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push
